import Link from 'next/link'
import './globals.css'
import styles from './layout.module.css'
import { Metadata } from 'next';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export const metadata: Metadata = {
  title: '기윤 제품 사이트',
  description: '기윤 제품 판매하는 곳',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <h1>Demo note</h1>
          <nav className={styles.nav}>
            <Link href="/products">Products</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
